CREATE TABLE people (
	guid TEXT PRIMARY KEY,
	firstName VARCHAR(100) NOT NULL,
	lastName VARCHAR(100) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	gender VARCHAR(50) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
	updatedAt TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE TABLE car(
	vin TEXT PRIMARY KEY NOT NULL,
	brand VARCHAR(100) NOT NULL,
	model VARCHAR(100) NOT NULL,
	year SMALLINT NOT NULL,
	color VARCHAR(100) NOT NULL
);

CREATE TABLE people_car (
	peopleId TEXT NOT NULL,
	carId TEXT NOT NULL,
	PRIMARY KEY (peopleId, carId),
	createdAt TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
	updatedAt TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
	CONSTRAINT fk_car FOREIGN KEY(carId) REFERENCES car(vin) ON DELETE CASCADE,
	CONSTRAINT fk_people FOREIGN KEY(peopleID) REFERENCES people(guid) ON DELETE CASCADE
);